elasticsearch:
  #image: elasticsearch:latest
  #command: elasticsearch -Des.network.host=0.0.0.0
  build: elasticsearch/
  ports:
    - "9200:9200"
logstash:
  image: logstash:2.0.0
  environment:
    - RUBYLIB=/mnt
  command: logstash -f /etc/logstash/conf.d/logstash.conf
  volumes:
    - ./logstash/config:/etc/logstash/conf.d
    - ./logstash/plugins:/mnt
  ports:
    - "5000:5000"
    - "5001:5001"
    - "25826:25826/udp"
  links:
    - elasticsearch
kibana:
  build: kibana/
  volumes:
    - ./kibana/config/kibana.yml:/opt/kibana/config/kibana.yml
  ports:
    - "5601:5601"
  links:
    - elasticsearch
