elasticsearch:
  image: 10.0.0.5:6000/elasticsearch:1112
  command: elasticsearch -Des.network.host=0.0.0.0
  ports:
    - "9200:9200"
logstash:
  image: 10.0.0.5:6000/logstash:1112
  environment:
    - RUBYLIB=/mnt
  command: logstash -f /etc/logstash/conf.d/logstash.conf
  volumes:
    - ./logstash/config:/etc/logstash/conf.d
    - ./logstash/plugins:/mnt
  ports:
    - "5000:5000"
    - "5001:5001"
    - "25826:25826/udp"
  links:
    - elasticsearch
kibana:
  image: 10.0.0.5:6000/kibana:1112
  volumes:
    - ./kibana/config/kibana.yml:/opt/kibana/config/kibana.yml
  ports:
    - "5601:5601"
  links:
    - elasticsearch
